version: '2.2'
services:
  satlas:
    container_name: satlas1_${UID}
    user: ${UID}
    env_file: .env
    build:
      context: ..
      args:
        UID: ${UID}
    shm_size: '8gb'
    cpuset: ${DOCKER_LIMIT_CPU_IDS}
    network_mode: host
    volumes:
      # this is the local directory
      - ../:/workspace/
      # keep torch/huggingface temp files from re-downloading every time
      - ../torch_tmp:/home/udocker/.cache/
      #needed for x-window-forwarding
      # execute this once per host system startup: xhost +local:docker
      - /tmp/.X11-unix:/tmp/.X11-unix
    #pwd: csync
    command: /bin/bash -c "jupyter notebook --ip=0.0.0.0 --port=${PORT0} --allow-root --no-browser --NotebookApp.password='sha1:26c148c4c3d7:f3fb45584ca8f933451d8e05e6861b54f3fe7822'"
